# Project information
site_name: Chaos Manager
site_author: Insurgentes Estelares
site_description: >-
  Documentação para do projeto Chaos Manager realizado na disciplina de
  Requisitos de Software na Universidade de Brasília


# Repository
repo_url: https://github.com/mdsreq-fga-unb/2023.2-ChaosManager
repo_name: Chaos Manager


# Configuration
docs_dir: docs
theme: 
  name: material
  language: pt-BR
  icon: 
   repo: fontawesome/brands/github
  font: 
    text: Roboto
  features:
  - navigation.instant
  - navigation.section
  - navigation.path
  - navigation.top
  - tabs

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
      primary: deep purple
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
      primary: deep purple
      accent: purple


# Page tree
nav: 
  - Início: index.md
  - Insurgentes Estelares: historia.md
  - Visão Geral do Produto: visao_produto.md
  - Visão Geral do Projeto: visao_projeto.md
  - Processo de Desenvolvimento: processo_software.md
  - Lições aprendidas: licoes.md

# Extensions
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences